---
- name: Create molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start uptime-kuma-instance container
      containers.podman.podman_container:
        name: uptime-kuma-instance
        image: docker.io/jrei/systemd-fedora:42
        state: started
        command: /sbin/init
        privileged: true
        systemd: always
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        cgroupns: host
