---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove uptime-kuma-instance container
      containers.podman.podman_container:
        name: uptime-kuma-instance
        state: absent
