---
- name: Create molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start podman-common-ubuntu-instance container
      containers.podman.podman_container:
        name: podman-common-ubuntu-instance
        image: docker.io/jrei/systemd-ubuntu:noble
        hostname: podman-common-ubuntu-instance
        state: started
        command: /sbin/init
        privileged: true
        systemd: always
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        cgroupns: host
