---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove podman-common-ubuntu-instance container
      containers.podman.podman_container:
        name: podman-common-ubuntu-instance
        state: absent
