---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove traefik-instance container
      containers.podman.podman_container:
        name: traefik-instance
        state: absent
