---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove arcane-instance container
      containers.podman.podman_container:
        name: arcane-instance
        state: absent
