# SPDX-License-Identifier: MIT
---
- name: Validate arguments against arg spec 'main'
  ansible.builtin.validate_argument_spec:
    argument_spec: "{{ (lookup('file', role_path + '/meta/argument_specs.yml') | from_yaml).argument_specs.main.options }}"

- name: Import hostname tasks
  ansible.builtin.import_tasks: hostname.yml

- name: Import package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Import firewalld tasks
  ansible.builtin.import_tasks: firewalld.yml

- name: Import SELinux tasks
  ansible.builtin.import_tasks: selinux.yml

- name: Import user tasks
  ansible.builtin.import_tasks: users.yml

- name: Import qemu-guest-agent tasks
  ansible.builtin.import_tasks: qemu.yml

- name: Import Cockpit tasks
  ansible.builtin.import_tasks: cockpit.yml

- name: Import Quadlet directory tasks
  ansible.builtin.import_tasks: quadlet_dir.yml
