# SPDX-License-Identifier: MIT
---
librechat_hostname: chat.example.com
librechat_data_dir: /opt/podman/librechat
librechat_port: 3080

# LibreChat API
librechat_api_image: ghcr.io/danny-avila/librechat:latest
librechat_mongo_uri: ""
librechat_jwt_secret: ""
librechat_jwt_refresh_secret: ""
librechat_creds_key: ""
librechat_creds_iv: ""

# Meilisearch
librechat_meilisearch_image: docker.io/getmeili/meilisearch:v1.7.3
librechat_meili_master_key: ""

# VectorDB (postgres for RAG)
librechat_vectordb_image: docker.io/ankane/pgvector:latest
librechat_vectordb_postgres_db: mydatabase
librechat_vectordb_postgres_user: myuser
librechat_vectordb_postgres_password: ""

# RAG API
librechat_ragapi_image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest

# Optional Obsidian vault bind mount
librechat_obsidian_mount_enabled: false
librechat_obsidian_mount_path: ""
