# SPDX-License-Identifier: MIT
---
- name: Install Cockpit and cockpit-podman
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-podman
    state: present
  become: true
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - common_cockpit_enabled

- name: Enable cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
  become: true
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - common_cockpit_enabled
