# SPDX-License-Identifier: MIT
---
- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Fedora'

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: true
    state: started
  become: true
  when: ansible_facts['distribution'] == 'Fedora'
