# SPDX-License-Identifier: MIT
---
- name: Enable and start qemu-guest-agent on KVM guests
  ansible.builtin.systemd:
    name: qemu-guest-agent.service
    enabled: true
    state: started
  become: true
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - ansible_facts['virtualization_type'] is defined
    - ansible_facts['virtualization_type'] == 'kvm'
