# SPDX-License-Identifier: MIT
---
- name: Set container_manage_cgroup SELinux boolean
  ansible.posix.seboolean:
    name: container_manage_cgroup
    state: true
    persistent: true
  become: true
  when: ansible_facts['selinux']['status'] != 'disabled'
