# SPDX-License-Identifier: MIT
---
- name: Ensure users exist with correct groups
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: true
    state: present
    shell: /bin/bash
  become: true
  loop: "{{ common_users }}"
  when: ansible_facts['distribution'] == 'Fedora'

- name: Deploy sudoers file for ansible service account
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/ansible
    mode: "0440"
    validate: visudo -cf %s
  become: true
  when: ansible_facts['distribution'] == 'Fedora'
