---
dependency:
  name: galaxy
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule:
        hosts:
          grimmory-instance:
            ansible_connection: containers.podman.podman
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
