---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove it-tools-instance container
      containers.podman.podman_container:
        name: it-tools-instance
        state: absent
